#!/bin/ksh

if [[ -z $1 ]]; then
	echo "usage: gcccomp srcfile"
	exit 1
fi >&2

OUTFILE=$1.tsk
echo c++ -Wnon-virtual-dtor -o $OUTFILE -I. -I./ay -I/opt/local/include $1 
c++ -o $OUTFILE -Wnon-virtual-dtor -I. -I/opt/local/include $1 
ls -l $OUTFILE
